### ISSUE TITLE
Installing from conda-envs results in upsupported python (3.13)

### ISSUE THREAD

**Issue by wd60622** [pymc-devs/pymc-extras#400]
Installing from yaml will result in dependency resolution error 

```bash
conda env create -f conda-envs/environement-test.yml
```

Notes: I am using `micromamba`

Pinning will likely cause issues with the CI/CD: 

https://github.com/wd60622/pymc-experimental/blob/5055262868473b61f487f42d82542f9d0fc0e273/.github/workflows/test.yml#L35-L42

Maybe some note about dev installation would be useful and sufficient

**Comment by ricardoV94** [comment]
> Pinning will likely cause issues with the CI/CD:

Why?

CC @maresb

**Comment by wd60622** [comment]
> Why?

Not sure if the duplicate key for python will be an issue or if the CI/CD lines that I linked will cause an issue if there is already a python key in env file

**Comment by ricardoV94** [comment]
Can we just do upper/lower pin in the yml?

**Comment by maresb** [comment]
I don't understand the formulation of this issue. Like what is even the expected vs actual behavior? What is the "dependency resolution error"?

**Comment by wd60622** [comment]
Putting lower and upper bounds in environment.yml will work. 

> I don't understand the formulation of this issue. Like what is even the expected vs actual behavior? What is the "dependency resolution error"?

I tried to install from yaml but python 3.13 was used didn't work with pymc versions

**Comment by maresb** [comment]
I think #403 should fix it since this should never happen on conda-forge

**Comment by wd60622** [comment]
> I think #403 should fix it since this should never happen on conda-forge

Alright. I will give it a try after merge

**Comment by wd60622** [comment]
Thanks for making the adjustment. 

Can confirm that 

```bash
gh repo fork pymc-devs/pymc-extras
cd pymc-extras
conda env create -f conda-envs/environment-test.yml
```

Builds an environment with compatible python version (3.12)

**Comment by maresb** [comment]
Excellent, thanks @wd60622 !
